feat: mirror node as a conditional subchart (#272)
Signed-off-by: Deepak Mishra <deepak@swirldslabs.com>
Signed-off-by: Lenin Mehedy <lenin.mehedy@swirldslabs.com>
Signed-off-by: Deepak Mishra <107930718+deepak-swirlds@users.noreply.github.com>
Signed-off-by: Nathan Klick <nathan@swirldslabs.com>
Co-authored-by: Lenin Mehedy <lenin.mehedy@swirldslabs.com>
Co-authored-by: Nathan Klick <nathan@swirldslabs.com>
Signed-off-by: Lenin Mehedy <lenin.mehedy@swirldslabs.com>

diff --git a/dev/Makefile b/dev/Makefile
--- a/dev/Makefile
+++ b/dev/Makefile
@@ -60,7 +60,13 @@ helm-test:
 	echo "" && \
 	echo ">> Running helm test..." && \
 	echo "" && \
-	helm test fst --logs
+	# We have to specify the specific test name here, otherwise it executes all tests from the subcharts as well.
+	# I had to remove --logs, because --logs ignores filter and tries to get logs for all test pods
+    #  - Error: unable to get pod logs for fst-graphql-test: pods "fst-graphql-test" not found
+	helm test fst --filter 'name=network-test' && \
+    EXIT_CODE=$$? && \
+	kubectl logs network-test && \
+	exit $${EXIT_CODE}
 
 .PHONY: deploy-network
 deploy-network: deploy-chart
