run prometheus operator through make and fullstack-cluster-setup
Signed-off-by: Jeromy Cannon <jeromy@swirldslabs.com>

diff --git a/dev/Makefile b/dev/Makefile
--- a/dev/Makefile
+++ b/dev/Makefile
@@ -63,10 +63,10 @@ update-helm-dependencies:
 
 .PHONY: init-shared
 init-shared:
-	echo "# values override file for fullstack-cluster-setup" > ${CLUSTER_SETUP_VALUES_FILE}
+	echo "cloud:" > ${CLUSTER_SETUP_VALUES_FILE}
 
 .PHONY: deploy-shared
-deploy-shared: init-shared update-helm-dependencies deploy-gateway-api deploy-prometheus-operator enable-minio-operator-if-required
+deploy-shared: init-shared update-helm-dependencies deploy-gateway-api enable-prometheus-operator enable-minio-operator-if-required
 	source "${SCRIPTS_DIR}/main.sh" && deploy_shared # run only after gateway-api CRDs are available
 
 .PHONY: destroy-shared
@@ -165,13 +165,25 @@ destroy-gateway-api:
 	source "${SCRIPTS_DIR}/${GATEWAY_API_SCRIPT}" && destroy_envoy_gateway_api
 
 ######################################### Telemetry #################################
-.PHONY: deploy-prometheus-operator
-deploy-prometheus-operator:
-	source "${SCRIPTS_DIR}/${TELEMETRY_SCRIPT}" && deploy-prometheus-operator
+.PHONY: enable-prometheus-operator-if-required
+enable-prometheus-operator-if-required:
+	@$(MAKE) is-prometheus-operator-installed || $(MAKE) enable-prometheus-operator
 
-.PHONY: destroy-prometheus-operator
-destroy-prometheus-operator:
-	source "${SCRIPTS_DIR}/${TELEMETRY_SCRIPT}" && destroy-prometheus-operator
+.PHONY: enable-prometheus-operator
+enable-prometheus-operator:
+	@echo ">> Enabling prometheus operator..."; \
+	echo "  prometheusOperator:" >> ${CLUSTER_SETUP_VALUES_FILE}; \
+	echo "    enable: true" >> ${CLUSTER_SETUP_VALUES_FILE};
+
+.PHONY: is-prometheus-operator-installed
+is-prometheus-operator-installed:
+	@echo ">> Checking for prometheus operator..."; \
+	kubectl get pods --all-namespaces | grep prometheus-operator &> /dev/null && { echo "Found prometheus operator."; exit 0; }; \
+	echo "Prometheus operator not found."; exit 1
+
+.PHONY: update-prometheus-operator
+update-prometheus-operator:
+	source "${SCRIPTS_DIR}/${TELEMETRY_SCRIPT}" && update-prometheus-operator
 
 .PHONY: deploy-grafana-tempo
 deploy-grafana-tempo:
@@ -182,7 +194,7 @@ destroy-grafana-tempo:
 	source "${SCRIPTS_DIR}/${TELEMETRY_SCRIPT}" && unexpose_grafana && destroy_grafana_tempo
 
 .PHONY: deploy-prometheus
-deploy-prometheus: deploy-prometheus-operator
+deploy-prometheus: enable-prometheus-operator
 	source "${SCRIPTS_DIR}/${TELEMETRY_SCRIPT}" && deploy-prometheus && expose_prometheus
 
 .PHONY: destroy-prometheus
@@ -202,7 +214,6 @@ destroy-telemetry-stack:
 .PHONY: enable-minio-operator
 enable-minio-operator:
 	@echo ">> Enabling minio operator..."; \
-	echo "cloud:" >> ${CLUSTER_SETUP_VALUES_FILE}; \
 	echo "  minio:" >> ${CLUSTER_SETUP_VALUES_FILE}; \
 	echo "    enable: true" >> ${CLUSTER_SETUP_VALUES_FILE};
 
