deploy minio operator if required
Signed-off-by: Deepak Mishra <deepak@swirldslabs.com>

diff --git a/dev/Makefile b/dev/Makefile
--- a/dev/Makefile
+++ b/dev/Makefile
@@ -116,7 +116,7 @@ run-func:
 	source "${SCRIPTS_DIR}/${SCRIPT_NAME}" && ${FUNC}
 
 .PHONY: start
-start: deploy-network setup-nodes start-nodes
+start: deploy-minio-operator-if-required deploy-network setup-nodes start-nodes
 
 .PHONY: restart
 restart: stop-nodes start-nodes
@@ -126,8 +126,22 @@ reset: destroy-network start
 
 .PHONY: deploy-minio-operator
 deploy-minio-operator:
-	echo ">> Deploying minio operator..." && \
-	helm install --repo https://operator.min.io/ --namespace=minio-operator --create-namespace minio-operator operator
+	@echo ">> Deploying minio operator..."; \
+	helm install --repo https://operator.min.io/ --namespace=minio-operator --create-namespace --version 5.0.7 minio-operator operator && \
+	echo ">> Waiting for minio operator to be ready..." && \
+	kubectl --namespace=minio-operator  wait --for=condition=available --timeout=600s deployment.apps/minio-operator && \
+	sleep 5
+
+.PHONY: is-minio-operator-installed
+is-minio-operator-installed:
+	@echo ">> Checking for minio operator..."; \
+	helm list --namespace=minio-operator | grep minio-operator &> /dev/null && { echo "Found minio operator."; exit 0; }; \
+	echo "Minio operator not found."; exit 1
+
+.PHONY: deploy-minio-operator-if-required
+deploy-minio-operator-if-required:
+	@make is-minio-operator-installed || make deploy-minio-operator
+
 
 .PHONY: undeploy-minio-operator
 undeploy-minio-operator:
