save
Signed-off-by: Jeffrey Tang <jeffrey@swirldslabs.com>

diff --git a/dev/Makefile b/dev/Makefile
--- a/dev/Makefile
+++ b/dev/Makefile
@@ -4,6 +4,7 @@ SHELL=/bin/bash
 # Ensure we can catch error to run cleanup when multiple make commands are run in sequence.
 # Here we tell make to run all scripts as one-shell and also set 'pipefail' and 'errexit' flags.
 # https://stackoverflow.com/questions/28597794/how-can-i-clean-up-after-an-error-in-a-makefile
+SHELLOPTS:=$(if $(SHELLOPTS),$(SHELLOPTS):)pipefail:errexit
 .ONESHELL:
 
 # Here we tell make not to output the actual command before execution in order to reduce noise in the logs.
@@ -106,12 +107,10 @@ destroy-network: destroy-test-container uninstall-chart
 
 .PHONY: setup-nodes
 setup-nodes: setup
-	echo "********************   Start setup-nodes  *******************"
 	source "${SCRIPTS_DIR}/${SCRIPT_NAME}" && setup_node_all
 
 .PHONY: start-nodes
 start-nodes:
-	echo "********************   Start start-nodes  *******************"
 	source "${SCRIPTS_DIR}/${SCRIPT_NAME}" && start_node_all
 
 .PHONY: verify-nodes
@@ -241,9 +240,16 @@ ci-test:
 	# We are only enabling this in this make target, however if necessary, similar pattern can be used in other targets.
 	# Ref: https://stackoverflow.com/questions/28597794/how-can-i-clean-up-after-an-error-in-a-makefile
 	# NOTE: It needs latest make (version ~=4.3)
+ifeq (${SCRIPT_NAME},nmt-install.sh)
+	$(MAKE) ci-deploy-network
+	# ignore error of setup-nodes and start-nodes for nmt-install.sh as NMT would fail when trying to delete symlinked files.
+	-$(MAKE) setup-nodes
+	-$(MAKE) start-nodes
+else
 	$(MAKE) ci-deploy-network setup-nodes start-nodes
+endif
 
 .PHONY: ci-deploy-network
 ci-deploy-network: setup-cluster local-kubectl-bats
 	$(MAKE) deploy-network CHART_VALUES_FILES="$(PWD)/ci/ci-values.yaml"
-	echo "********************   Done with deploy-network  *******************"
+	$(MAKE) helm-test
