chore(ci): publish CLI to Github NPM package registry (#445)
Signed-off-by: Lenin Mehedy <lenin.mehedy@swirldslabs.com>

diff --git a/.github/workflows/flow-deploy-release-artifact.yaml b/.github/workflows/flow-deploy-release-artifact.yaml
--- a/.github/workflows/flow-deploy-release-artifact.yaml
+++ b/.github/workflows/flow-deploy-release-artifact.yaml
@@ -80,7 +80,10 @@ jobs:
 
       - name: Extract Version
         id: tag
-        run: echo "version=$(cat VERSION | tr -d '[:space:]')" >> ${GITHUB_OUTPUT}
+        run: |
+          cat VERSION
+          [[ ! -f VERSION ]] && echo "VERSION file is not found" && exit 1  # error on missing VERSION file
+          echo "version=$(cat VERSION | tr -d '[:space:]')" >> ${GITHUB_OUTPUT}
 
   publish-maven-central:
     name: Publish
@@ -154,12 +157,34 @@ jobs:
           push: ${{ github.event.inputs.dry-run-enabled != 'true' }}
           tags: ghcr.io/${{ github.repository }}/kubectl-bats:${{ needs.prepare-release.outputs.version }}
 
+  publish-npm-packages:
+    name: Publish / NPM Packages
+    runs-on: [self-hosted, Linux, medium, ephemeral]
+    needs:
+      - prepare-release
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
+      - name: Install Node
+        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
+        with:
+          node-version: 18
+      - name: Publish NPM Package
+        working-directory: "fullstack-network-manager"
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          npm ci 
+          npm i replace-json-property && ./node_modules/replace-json-property/bin/replace-json-property.bin.js package.json version ${{ needs.prepare-release.outputs.version }} && cat package.json | grep 'version'
+          npm publish ${{ github.event.inputs.dry-run-enabled && '--dry-run' || '' }}
+
   create-github-release:
     name: Github / Release
     runs-on: [self-hosted, Linux, medium, ephemeral]
     needs:
       - publish-maven-central
       - publish-docker-image
+      - publish-npm-packages
     if: ${{ github.event.inputs.dry-run-enabled != 'true' && !cancelled() && !failure() }}
     steps:
       - name: Checkout Code
