ci: fix bash file check
Signed-off-by: Lenin Mehedy <lenin.mehedy@swirldslabs.com>

diff --git a/.github/workflows/flow-deploy-release-artifact.yaml b/.github/workflows/flow-deploy-release-artifact.yaml
--- a/.github/workflows/flow-deploy-release-artifact.yaml
+++ b/.github/workflows/flow-deploy-release-artifact.yaml
@@ -82,7 +82,7 @@ jobs:
         id: tag
         run: |
           cat VERSION
-          [[ ! -f "${VERSION}" ]] && exit 1  # error on missing VERSION file
+          [[ ! -f VERSION ]] && echo "VERSION file is not found" && exit 1  # error on missing VERSION file
           echo "version=$(cat VERSION | tr -d '[:space:]')" >> ${GITHUB_OUTPUT}
 
   publish-maven-central:
