add
Signed-off-by: Jeffrey Tang <jeffrey@swirldslabs.com>

diff --git a/.github/workflows/zxc-helm-chart-tests.yaml b/.github/workflows/zxc-helm-chart-tests.yaml
--- a/.github/workflows/zxc-helm-chart-tests.yaml
+++ b/.github/workflows/zxc-helm-chart-tests.yaml
@@ -51,12 +51,6 @@ jobs:
         # nmt-install.sh uses ubi8-init-dind image
         scriptName: [ direct-install.sh, nmt-install.sh  ]
     steps:
-      - name: Setup Make
-        run: |
-          if ! command -v make >/dev/null 2>&1; then
-            sudo apt-get update
-            sudo apt-get install -y make
-          fi
       - name: Get changed files related to charts
         id: changed-files
         uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959 #v42.0.2
@@ -138,6 +132,138 @@ jobs:
         if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
         run: |
           echo "Running test with SCRIPT_NAME=${{ steps.vars.outputs.script_name}}"
-          sleep 7200
           
+          #SCRIPT_NAME=${{ steps.vars.outputs.script_name }}
+          
+          CUR_DIR="scripts"
+          source "${CUR_DIR}/env.sh"
+          
+          kind create cluster -n "${CLUSTER_NAME}" --config=dev-cluster.yaml
 
+          cp "${SCRIPT_DIR}/template.env" "${TMP_DIR}/.env"
+    
+          set -a
+          source "${TMP_DIR}/.env"
+          
+          kubectl create ns "${NAMESPACE}"
+          kubectl get ns
+          kubectl config use-context "kind-${CLUSTER_NAME}"
+          kubectl config set-context --current --namespace="${NAMESPACE}"
+          kubectl config get-contexts
+          
+          KUBECTL_BATS_IMAGE="${LOCAL_DOCKER_REGISTRY}/kubectl-bats:${LOCAL_DOCKER_IMAGE_TAG}"
+          echo ""
+          echo "Building kubectl-bats image"
+          echo "-----------------------------------------------------------------------------------------------------"
+          cd "${DOCKERFILE_DIR}/kubectl-bats" && docker build -t "${KUBECTL_BATS_IMAGE}" .
+          kind load docker-image "${KUBECTL_BATS_IMAGE}" -n "${CLUSTER_NAME}"
+          cd -
+          
+          CHART_VALUES_FILES=ci/ci-values.yaml
+          # TMP_DIR=temp
+
+
+          SCRIPTS_DIR=scripts
+          SCRIPT_NAME=direct-install.sh
+          TELEMETRY_SCRIPT="telemetry.sh"
+          GATEWAY_API_SCRIPT="gateway.sh"
+          DOCKER_SCRIPT="docker.sh"
+  
+          echo "make deploy-network CHART_VALUES_FILES=ci/ci-values.yaml"
+  
+          
+          # CLUSTER_SETUP_VALUES_FILE=${TMP_DIR}/cluster-values.yaml
+          
+          echo "cloud:" > ${CLUSTER_SETUP_VALUES_FILE}
+          echo "  prometheusStack:" >> ${CLUSTER_SETUP_VALUES_FILE}; \
+          echo "    enabled: true" >> ${CLUSTER_SETUP_VALUES_FILE};
+          
+          echo "  minio:" >> ${CLUSTER_SETUP_VALUES_FILE}; \
+          echo "    enabled: true" >> ${CLUSTER_SETUP_VALUES_FILE};
+          
+          
+          
+          helm dependency update ../charts/fullstack-deployment
+          helm dependency update ../charts/fullstack-cluster-setup
+          
+          # echo "enable-prometheus-stack-if-required enable-minio-operator-if-required"
+          # echo enable-prometheus-stack-if-required enable-minio-operator-if-required
+          
+          
+          helm install -n "${NAMESPACE}" "fullstack-cluster-setup" "${SETUP_CHART_DIR}" --values "${CLUSTER_SETUP_VALUES_FILE}"
+          echo "-----------------------Shared Resources------------------------------------------------------------------------------"
+          kubectl get clusterrole "${POD_MONITOR_ROLE}" -o wide
+  
+          
+          echo ""
+          echo "Installing helm chart... "
+          echo "SCRIPT_NAME: ${SCRIPT_NAME}"
+          echo "Additional values: ${CHART_VALUES_FILES}"
+          echo "-----------------------------------------------------------------------------------------------------"
+          if [ "${SCRIPT_NAME}" = "nmt-install.sh" ]; then
+            nmt_install
+          else
+            if [[ -z "${CHART_VALUES_FILES}" ]]; then
+              helm install "${RELEASE_NAME}" -n "${NAMESPACE}" "${CHART_DIR}"
+            else
+              helm install "${RELEASE_NAME}" -n "${NAMESPACE}" "${CHART_DIR}" -f "${CHART_DIR}/values.yaml" --values "${CHART_VALUES_FILES}"
+            fi
+          fi
+    
+          
+          # source scripts/main.sh && install_chart "${SCRIPT_NAME}"
+          
+          
+          echo "" && \
+          echo ">> Service Information...." && \
+          echo "" && \
+          kubectl get svc -o wide && \
+          echo "" && \
+          echo ">> Pod Information...." && \
+          echo "" && \
+          kubectl get pods -o wide && \
+          echo ">> Waiting for network-node pods to be active (first deployment takes ~10m)...." && \
+          kubectl wait --for=jsonpath='{.status.phase}'=Running pod -l fullstack.hedera.com/type=network-node --timeout=900s
+          echo "" && \
+          echo ">> Service Information...." && \
+          echo "" && \
+          kubectl get svc -o wide && \
+          echo ">> Waiting for pods to be up (timeout 600s)" && \
+          kubectl wait --for=jsonpath='{.status.phase}'=Running pod -l fullstack.hedera.com/type=network-node --timeout=600s
+  
+          # make helm-test
+          # run_helm_chart_tests "network-test"
+          echo ""
+          echo "Running helm chart tests (takes ~5m, timeout 15m)... "
+          echo "-----------------------------------------------------------------------------------------------------"
+          
+          helm test "${RELEASE_NAME}" --filter name=network-test --timeout 15m
+          
+          #make setup-nodes
+          source "${SCRIPTS_DIR}/${SCRIPT_NAME}" && setup_node_all
+          
+          #make start-nodes
+          source "${SCRIPTS_DIR}/${SCRIPT_NAME}" && start_node_all
+          
+          #make destroy-network
+          # make destroy-test-container
+  
+          echo ">> Deleting test container..." && \
+          kubectl delete pod network-test -n "${NAMESPACE}" || true          
+  
+          #make uninstall-chart
+          echo "Uninstalling helm chart ${RELEASE_NAME} in namespace ${NAMESPACE}... "
+          echo "-----------------------------------------------------------------------------------------------------"
+          helm uninstall -n "${NAMESPACE}" "${RELEASE_NAME}"
+          sleep 10
+          echo "Uninstalled helm chart ${RELEASE_NAME} in namespace ${NAMESPACE}"
+
+          has_secret=$(kubectl get secret | grep -c "sh.helm.release.v1.${RELEASE_NAME}.*")
+          if [[ $has_secret ]]; then
+            kubectl delete secret "sh.helm.release.v1.${RELEASE_NAME}.v1" || true
+          fi
+        
+          has_postgres_pvc=$(kubectl get pvc --no-headers -l app.kubernetes.io/component=postgresql,app.kubernetes.io/name=postgres,app.kubernetes.io/instance="${RELEASE_NAME}" | wc -l)
+          if [[ $has_postgres_pvc ]]; then
+            kubectl delete pvc -l app.kubernetes.io/component=postgresql,app.kubernetes.io/name=postgres,app.kubernetes.io/instance="${RELEASE_NAME}"
+          fi
