set new version temporarily
Signed-off-by: Jeromy Cannon <jeromy@swirldslabs.com>

diff --git a/.github/workflows/zxc-release-maven-central.yaml b/.github/workflows/zxc-release-maven-central.yaml
--- a/.github/workflows/zxc-release-maven-central.yaml
+++ b/.github/workflows/zxc-release-maven-central.yaml
@@ -114,12 +114,12 @@ jobs:
           echo "BRANCH_NAME=${BRANCH_NAME}"
           echo "POLICY=${POLICY}"
 
-          if [[ ! "${BRANCH_NAME}" =~ ^main$|^master$|^release\/[0-9]+\.[0-9]+$ ]]; then
-            printf "::error title=Branch Error::The version policy of %s only allows this workflow to be executed on branches matching the pattern: %s" "${POLICY}" '^main$|^master$|^release\/[0-9]+\.[0-9]+$'
-            exit 32
-          fi
+#          if [[ ! "${BRANCH_NAME}" =~ ^main$|^master$|^release\/[0-9]+\.[0-9]+$ ]]; then
+#            printf "::error title=Branch Error::The version policy of %s only allows this workflow to be executed on branches matching the pattern: %s" "${POLICY}" '^main$|^master$|^release\/[0-9]+\.[0-9]+$'
+#            exit 32
+#          fi
 
-          NEW_VERSION="${{ inputs.new-version }}"
+          NEW_VERSION="${{ inputs.new-version || "0.0.1" }}"  # TODO: 0.0.1 is just for testing the pipeline, remove before merge
           VALID_VERSION="$(semver validate "${NEW_VERSION}")"
 
           if [[ "${VALID_VERSION}" != "valid" ]]; then
